xxx yolos

what do we need for yolo?
get all the labeld images?

transfrome labels?

weights?


In [92]:
from transformers import AutoModelForObjectDetection,AutoImageProcessor
from PIL import Image, ImageDraw

import pandas as pd
import torch
import cv2 as cv
import numpy as np
import shutil
import os



In [ ]:
image_processor = AutoImageProcessor.from_pretrained("hustvl/yolos-base")
model = AutoModelForObjectDetection.from_pretrained("hustvl/yolos-base")

In [ ]:
img = Image.open("tomo_00e463/slice_0235.jpg")
test_img=image_processor(images=img, return_tensors="pt")


In [ ]:
img

In [ ]:

outputs = model(**test_img)
#model.bbox_predictor(**test_img)

In [ ]:
target_sizes = torch.tensor([img.size[::-1]])

results = image_processor.post_process_object_detection(outputs, threshold=0.9, target_sizes=target_sizes)[

    0

]

In [ ]:
from transformers import YolosFeatureExtractor, YolosForObjectDetection

grayscale_image = Image.open("tomo_00e463/slice_0235.jpg").convert("L")

# Convert to RGB
rgb_image = Image.merge("RGB", (grayscale_image, grayscale_image, grayscale_image))

# Save the RGB image
rgb_image.save("rgb_test_img.jpg")
img = Image.open("rgb_test_img.jpg")

feature_extractor = YolosFeatureExtractor.from_pretrained('hustvl/yolos-base')
model = YolosForObjectDetection.from_pretrained('hustvl/yolos-base')

inputs = feature_extractor(images=img, return_tensors="pt")
outputs = model(**inputs)

In [ ]:
logits = outputs.logits
bboxes = outputs.pred_boxes

In [ ]:
bboxes

In [ ]:
target_sizes = torch.tensor([[img.size[1], img.size[0]]])
results = image_processor.post_process_object_detection(outputs, threshold=0.005, target_sizes=target_sizes)[0]


In [ ]:
results

In [ ]:
for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):

    box = [round(i, 2) for i in box.tolist()]

    print(

        f"Detected {model.config.id2label[label.item()]} with confidence "

        f"{round(score.item(), 3)} at location {box}"

    )

In [ ]:
draw = ImageDraw.Draw(img)

for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):

    box = [round(i, 2) for i in box.tolist()]

    x, y, x2, y2 = tuple(box)

    draw.rectangle((x, y, x2, y2), outline="red", width=1)

    draw.text((x, y), model.config.id2label[label.item()], fill="white")

img

---
## Fine Tune/ Transfer Modell

In [3]:
df=pd.read_csv("train_labels.csv")

In [18]:
df.head(2)

row_id      tomo_id  Motor axis 0  Motor axis 1  Motor axis 2  \
0       0  tomo_003acc          -1.0          -1.0          -1.0   
1       1  tomo_00e047         169.0         546.0         603.0   

   Array shape (axis 0)  Array shape (axis 1)  Array shape (axis 2)  \
0                   500                  1912                  1847   
1                   300                   959                   928   

   Voxel spacing  Number of motors  
0            6.5                 0  
1           15.6                 1

In [40]:
df["Voxel spacing"].value_counts()

Voxel spacing
13.1    291
15.6    177
19.7    104
16.8     85
16.1     40
13.3     18
19.3     10
19.2      7
6.5       3
13.2      2
Name: count, dtype: int64

In [33]:
print(df[df["Motor axis 0"]!=-1]["Motor axis 0"].nsmallest(5))
print(df[df["Motor axis 1"]!=-1]["Motor axis 1"].nsmallest(5))
print(df[df["Motor axis 2"]!=-1]["Motor axis 2"].nsmallest(5))

366     0.0
291     3.0
48     16.0
656    21.0
72     24.0
Name: Motor axis 0, dtype: float64
474    59.0
694    64.0
422    67.0
584    72.0
421    80.0
Name: Motor axis 1, dtype: float64
689    30.0
380    41.0
26     45.0
25     54.0
97     58.0
Name: Motor axis 2, dtype: float64


In [12]:
print(df["Array shape (axis 0)"].unique())
print(df["Array shape (axis 1)"].unique())
print(df["Array shape (axis 2)"].unique())

[500 300 600 800 400 494]
[1912  959  924  960  928 1024  927  956]
[1847  928  956  960 1440  959  924]


In [9]:
#print(len(df[df["Array shape (axis 1)"]!=959]))
print(len(df[df["Array shape (axis 1)"]!=959]))
print(len(df[df["Array shape (axis 2)"]!=928]))

663
281


In [34]:
print(len(df[df["Motor axis 0"]!=-1]))
print(len(df[df["Motor axis 1"]!=-1]))
print(len(df[df["Motor axis 2"]!=-1]))

451
451
451


In [39]:
print(len(df[df["Motor axis 0"]!=-1]["tomo_id"].unique()))
print(len(df[df["Motor axis 1"]!=-1]["tomo_id"].unique()))
print(len(df[df["Motor axis 2"]!=-1]["tomo_id"].unique()))

362
362
362


In [28]:
df[df["Motor axis 0"]==466]

row_id      tomo_id  Motor axis 0  Motor axis 1  Motor axis 2  \
692     692  tomo_ec607b         466.0         458.0         301.0   

     Array shape (axis 0)  Array shape (axis 1)  Array shape (axis 2)  \
692                   500                   928                   960   

     Voxel spacing  Number of motors  
692           13.1                 2

In [23]:
df[df["Motor axis 2"]!=-1]["Motor axis 2"].min()

np.float64(30.0)

In [24]:
df_bbox=df.iloc[:,1:6]
labels=df_bbox.values
labels

array([['tomo_003acc', -1.0, -1.0, -1.0, 500],
       ['tomo_00e047', 169.0, 546.0, 603.0, 300],
       ['tomo_00e463', 235.0, 403.0, 137.0, 500],
       ...,
       ['tomo_fea6e8', -1.0, -1.0, -1.0, 300],
       ['tomo_ff505c', 111.0, 816.0, 678.0, 300],
       ['tomo_ff7c20', -1.0, -1.0, -1.0, 800]],
      shape=(737, 5), dtype=object)

In [44]:
np.arange(4,8)

array([4, 5, 6, 7])

In [113]:
# Create YOLO format label
# YOLO format: <class> <x_center> <y_center> <width> <height>
# Values are normalized to [0, 1]
# {"file_name": "0001.png", "objects": {"bbox": [[302.0, 109.0, 73.0, 52.0]], "categories": [0]}}
BBOXS_SIZE = 28
detections = []
detections_empty = []
trust = 4

for a in labels:
    if a[1] != -1:
        for b in np.arange(int(a[1])-trust, int(a[1])+trust+1):
            detections.append({"file_name": f"{a[0]}/slice_{b:04d}.jpg", "object": {
                              "bbox": [0, a[-2], a[2], BBOXS_SIZE, BBOXS_SIZE], "categories": [0]}})
    else:
        random_slice = np.random.choice(a[-1], size=3)
        for c in random_slice:
            detections_empty.append(
                {"file_name": f"{a[0]}/slice_{c:04d}.jpg", "object": {"bbox": [], "categories": []}})

print(len(detections))
print(len(detections_empty))

print(f"portion of empty = {len(detections_empty)/len(detections)}")

# Train test split
split=0.1
size_det = len(detections)
size_empt = len(detections_empty)

test_split_det = int(size_det*split)
test_split_empt= int(size_empt*split)

indices_test_det = np.random.choice(size_det, size=test_split_det)
indices_test_empt= np.random.choice(size_empt, size=test_split_empt)



#copy test files

for i in indices_test_det:
    if detections[i]["object"]["bbox"][1]>=0:
        source="train/"+detections[i]["file_name"]
        destination = "test/"+detections[i]["file_name"]

        if not os.path.isdir(os.path.dirname(destination)):
            os.mkdir(os.path.dirname(destination))
                  
        shutil.copyfile(source, destination)


for i in indices_test_empt:
    
    source="train/"+detections_empty[i]["file_name"]
    destination = "test/"+detections_empty[i]["file_name"]

    if not os.path.isdir(os.path.dirname(destination)):
        os.mkdir(os.path.dirname(destination))
                
    shutil.copyfile(source, destination)

# Create YAML configuration file for YOLO
"""yaml_content = {
    'path': yolo_dataset_dir,
    'train': 'images/train',
    'val': 'images/val',
    'names': {0: 'motor'}
}"""
print(len(indices_test_det))
print(len(indices_test_empt))

4059
858
portion of empty = 0.21138211382113822
405
85


In [109]:
destination = detections[2]["file_name"]
if not os.path.isdir(os.path.dirname("test/"+destination)):
    os.mkdir(os.path.dirname("test/"+destination))


In [76]:
detections[2]["file_name"].split("/")[1]

'slice_0167.jpg'

In [64]:
2255*0.253658

571.99879

In [20]:
test_split=int(len(df.index)*0.15)
test_split

110

In [26]:
detections

[{'file_name': 'tomo_00e047/slice_0169.jpg',
  'object': {'bbox': [0, 603.0, 546.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_00e463/slice_0235.jpg',
  'object': {'bbox': [0, 137.0, 403.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_00e463/slice_0243.jpg',
  'object': {'bbox': [0, 153.0, 363.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_00e463/slice_0222.jpg',
  'object': {'bbox': [0, 144.0, 379.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_00e463/slice_0225.jpg',
  'object': {'bbox': [0, 628.0, 262.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_00e463/slice_0225.jpg',
  'object': {'bbox': [0, 643.0, 241.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_00e463/slice_0231.jpg',
  'object': {'bbox': [0, 632.0, 289.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_01a877/slice_0147.jpg',
  'object': {'bbox': [0, 286.0, 638.0, 28, 28], 'categories': [0]}},
 {'file_name': 'tomo_02862f/slice_0101.jpg',
  'object': {'bbox': [0, 120.0, 351.0, 28, 

In [ ]:

MAX_SIZE = IMAGE_SIZE

image_processor = AutoImageProcessor.from_pretrained(

    "hustvl/yolos-base",

    do_resize=True,

    size={"max_height": MAX_SIZE, "max_width": MAX_SIZE},

    do_pad=True,

    pad_size={"height": MAX_SIZE, "width": MAX_SIZE},

)
